package ecommerce_design_interior.repositories.dataAccessAbstracts;

import ecommerce_design_interior.entities.products.productsdDetails.DesignDescriptionEntity;
import org.springframework.data.jpa.repository.JpaRepository;

public interface DesignDescriptionRepository extends JpaRepository<DesignDescriptionEntity,Long> {}